version: "3.7"

services:
  requester-node:
    command: inferenced start
    image: inferenced
    volumes:
      - ./prod-sim/requester:/root/.inference
    networks:
      - net-public

  requester-api:
    image: decentralized-api
    volumes:
      - ./prod-sim/requester:/root/.inference
    ports:
      - "8080:8080"
    environment:
      - API_CONFIG_PATH=/root/.inference/api-config.yaml
    networks:
      net-public:

  executor-node:
    command: inferenced start
    image: inferenced
    volumes:
      - ./prod-sim/executor:/root/.inference
    networks:
      - net-public

  executor-api:
    image: decentralized-api
    volumes:
      - ./prod-sim/executor:/root/.inference
    ports:
      - "8081:8080"
    environment:
      - API_CONFIG_PATH=/root/.inference/api-config.yaml
    networks:
      net-public:

  validator-node:
    command: inferenced start
    image: inferenced
    volumes:
      - ./prod-sim/validator:/root/.inference
    networks:
      - net-public

  validator-api:
    image: decentralized-api
    volumes:
      - ./prod-sim/validator:/root/.inference
    ports:
      - "8082:8080"
    environment:
      - API_CONFIG_PATH=/root/.inference/api-config.yaml
    networks:
      net-public:

networks:
  net-public:
