services:
  requester-node:
    command: inferenced start
    image: inferenced
    volumes:
      - ./prod-sim/requester:/root/.inference
    networks:
      - chain-public

  requester-api:
    image: decentralized-api
    volumes:
      - ./prod-sim/requester:/root/.inference
    ports:
      - "8080:8080"
    environment:
      - API_CONFIG_PATH=/root/.inference/api-config.yaml
    networks:
      - chain-public

  executor-node:
    command: inferenced start
    image: inferenced
    volumes:
      - ./prod-sim/executor:/root/.inference
    networks:
      - chain-public

  executor-api:
    image: decentralized-api
    volumes:
      - ./prod-sim/executor:/root/.inference
    ports:
      - "8081:8080"
    environment:
      - API_CONFIG_PATH=/root/.inference/api-config.yaml
    networks:
      - chain-public

  validator-node:
    command: inferenced start
    image: inferenced
    volumes:
      - ./prod-sim/validator:/root/.inference
    networks:
      - chain-public

  validator-api:
    image: decentralized-api
    volumes:
      - ./prod-sim/validator:/root/.inference
    ports:
      - "8082:8080"
    environment:
      - API_CONFIG_PATH=/root/.inference/api-config.yaml
    networks:
      - chain-public

networks:
  chain-public:
    # Gives a stable name across projects
    name: chain-public
