version: "3.7"

services:
  node:
    container_name: node
    image: gcr.io/decentralized-ai/inferenced
    command: ["sh", "./init-docker-genesis.sh"]
    volumes:
      - .inference:/root/.inference
    environment:
      - KEY_NAME=${KEY_NAME}
    ports:
      - "26656:26656" #p2p
      - "26657:26657" #rpc
  api:
    container_name: api
    image: gcr.io/decentralized-ai/api
    depends_on:
      - node
    environment:
      - KEY_NAME=${KEY_NAME}
      - POC_CALLBACK_URL=${POC_CALLBACK_URL}
      - PORT=${PORT}
    ports:
      - "${PORT}:8080"
    # It shares the volume with the node, because it needs access to the keyring
    volumes:
      - .inference:/root/.inference
