services:
  node:
    container_name: node
    image: gcr.io/decentralized-ai/inferenced
    command: ["sh", "./init-docker.sh"]
    volumes:
      - .inference:/root/.inference
    environment:
      - SEED_NODE_RPC_URL=${SEED_NODE_RPC_URL}
      - SEED_NODE_P2P_URL=${SEED_NODE_P2P_URL}
      - KEY_NAME=${KEY_NAME}
    ports:
      - "26656:26656" #p2p
      - "26657:26657" #rpc

  api:
    container_name: api
    image: gcr.io/decentralized-ai/api
    volumes:
      - .inference:/root/.inference
      - ./${NODE_CONFIG}:/root/node_config.json
    depends_on:
      - node
    environment:
      - KEY_NAME=${KEY_NAME}
      - DAPI_API__POC_CALLBACK_URL=${POC_CALLBACK_URL}
      - DAPI_API__PUBLIC_URL=${PUBLIC_URL}
      - DAPI_CHAIN_NODE__SEED_API_URL=${SEED_API_URL}
      - NODE_CONFIG_PATH=/root/node_config.json
    ports:
      - "${PORT}:8080"
    # It shares the volume with the node, because it needs access to the keyring
