apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
- name: api
  newName: ghcr.io/product-science/api
  newTag: 0.1.2
- name: node
  newName: ghcr.io/product-science/inferenced
  newTag: 0.1.2
- name: inference
  newName: ghcr.io/product-science/mlnode
  newTag: 3.0.4-alpha2-bcstore-test-0.2
- name: tmkms
  newName: ghcr.io/product-science/tmkms-softsign-with-keygen
  newTag: 32165a2
- name: proxy
  newName: ghcr.io/product-science/proxy
  newTag: 1.1.2
- name: explorer
  newName: ghcr.io/product-science/explorer
  newTag: latest
